version: "3.9"
services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: optic
    ports:
      - "5432:5432"
    volumes:
      - app-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
    container_name: app
    depends_on:
      - postgres
    links:
      - postgres
    ports:
      - "8080:8080"

volumes:
  app-db:
